# Generated by Django 5.2 on 2025-04-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Detention Reason',
                'verbose_name_plural': 'Detention Reasons',
            },
        ),
        migrations.CreateModel(
            name='DetentionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Detention Status',
                'verbose_name_plural': 'Detention Statuses',
            },
        ),
        migrations.CreateModel(
            name='PDLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDL Profile',
                'verbose_name_plural': 'PDL Profiles',
            },
        ),
        migrations.CreateModel(
            name='DetentionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_term_length', models.IntegerField(default=0, verbose_name='Detention Term Length')),
                ('detention_start_date', models.DateField(verbose_name='Detention Start Date')),
                ('detention_end_date', models.DateField(blank=True, null=True, verbose_name='Detention End Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('detention_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionreason', verbose_name='Detention Reason')),
                ('detention_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionstatus', verbose_name='Detention Status')),
                ('pdl_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.pdlprofile', verbose_name='PDL Profile')),
            ],
            options={
                'verbose_name': 'Detention Instance',
                'verbose_name_plural': 'Detention Instances',
                'ordering': ['-detention_start_date'],
            },
        ),
    ]
