# Generated by Django 5.2 on 2025-09-25 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentioninstance',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='case',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Case Number'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced'), ('SEP', 'Separated'), ('LI', 'Live-in / Domestic partnership')], max_length=3, null=True, verbose_name='Civil Status'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='contact_person_address',
            field=models.TextField(blank=True, verbose_name='Address of Contact Person'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email of Contact Person'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Contact Person'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Phone of Contact Person'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='contact_person_relationship',
            field=models.CharField(blank=True, max_length=128, verbose_name='Relationship to Contact Person'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='date_of_commitment',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Commitment'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('NONE', 'No formal schooling'), ('ELEM', 'Elementary'), ('HS', 'High School'), ('SHS', 'Senior High School'), ('VOC', 'Vocational/Technical'), ('COL', 'College/Undergraduate'), ('POST', 'Postgraduate')], max_length=5, null=True, verbose_name='Educational Attainment'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='name_of_jail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Jail'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='origin_lockup',
            field=models.CharField(blank=True, max_length=255, verbose_name='Origin Lockup'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='place_of_birth_country',
            field=models.CharField(blank=True, max_length=128, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='place_of_birth_municipality',
            field=models.CharField(blank=True, max_length=128, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='place_of_birth_province',
            field=models.CharField(blank=True, max_length=128, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='place_of_birth_region',
            field=models.CharField(blank=True, max_length=128, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='detentioninstance',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex'),
        ),
    ]
