# Generated by Django 5.2 on 2025-09-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0003_remove_detentioninstance_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionreason', verbose_name='Detention Reason'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Detention Start Date'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionstatus', verbose_name='Detention Status'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_term_length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Detention Term Length'),
        ),
    ]
