# Generated by Django 5.2 on 2025-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0004_alter_detentioninstance_detention_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentioninstance',
            name='detention_room_number',
            field=models.CharField(blank=True, null=True, verbose_name='Detention Room Number'),
        ),
    ]
