# Generated by Django 5.2 on 2025-09-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0006_pdlprofile_middle_name_pdlprofile_name_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdlprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='pdlprofile',
            name='name_suffix',
        ),
    ]
