# Generated by Django 5.2 on 2025-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0007_remove_pdlprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Middle Name(s)'),
        ),
        migrations.AddField(
            model_name='pdlprofile',
            name='name_suffix',
            field=models.CharField(blank=True, choices=[('', '(none)'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('MD', 'MD'), ('PhD', 'PhD'), ('Esq.', 'Esq.')], default='', help_text='e.g., Jr., Sr., II, III; leave blank if none.', max_length=10, verbose_name='Name Suffix'),
        ),
    ]
