# Generated by Django 5.2 on 2025-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0008_pdlprofile_middle_name_pdlprofile_name_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture URL'),
        ),
    ]
