# Generated by Django 5.2 on 2026-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0009_pdlprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_room_number',
            field=models.CharField(max_length=50, verbose_name='Detention Room Number'),
        ),
    ]
