# Generated by Django 5.2 on 2026-03-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0010_alter_detentioninstance_detention_room_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('HTN', 'Hypertension'), ('DM', 'Diabetes Mellitus'), ('HEART', 'Heart Disease'), ('ASTHMA', 'Asthma / COPD'), ('TB', 'Tuberculosis'), ('MENTAL', 'Mental Health Condition'), ('RENAL', 'Kidney Disease'), ('CANCER', 'Cancer'), ('OTHER', 'Other')], max_length=10)),
                ('date_diagnosed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdl_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='pdl.pdlprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Condition',
                'verbose_name_plural': 'Health Conditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('doctor', 'Doctor / Nurse'), ('pharmacist', 'Pharmacist')], default='staff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
