# Generated by Django 5.2 on 2026-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0011_healthcondition_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentionreason',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='detentionreason',
            name='reason',
            field=models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Drug Possession', 'Drug Possession'), ('Fraud', 'Fraud'), ('Vandalism', 'Vandalism')], max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='detentionstatus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='detentionstatus',
            name='status',
            field=models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Released', 'Released'), ('Transferred', 'Transferred'), ('On Bail', 'On Bail'), ('Escaped', 'Escaped')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor / Nurse'), ('pharmacist', 'Pharmacist')], default='doctor', max_length=20),
        ),
    ]
