# Generated by Django 5.2 on 2026-03-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0012_alter_detentionreason_description_and_more'),
        ('pdl', '0012_remove_staff_role'),
    ]

    operations = [
    ]
