# Generated by Django 5.2 on 2026-01-06 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationprescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medication Prescription', 'verbose_name_plural': 'Medication Prescriptions'},
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum quantity before reorder'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.pharmacist'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='quantity_dispensed',
            field=models.IntegerField(default=0, help_text='Quantity already dispensed'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='quantity_prescribed',
            field=models.IntegerField(default=0, help_text='Total quantity prescribed'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('partially_dispensed', 'Partially Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current quantity in stock'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('addition', 'Stock Addition'), ('dispensation', 'Dispensation'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('expired', 'Expired/Disposed')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for dispensations')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='medications.medicationinventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medicationprescription')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
