# Generated by Django 5.2 on 2026-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medicationprescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationprescription',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('dispensed', 'Dispensed')], default='pending', max_length=20),
        ),
    ]
