# Generated by Django 5.2 on 2026-02-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medicationprescription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicationgenericname',
            options={'verbose_name_plural': 'Medication Generic Names'},
        ),
        migrations.AlterModelOptions(
            name='medicationinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicationprescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicationtype',
            options={'verbose_name_plural': 'Medication Types'},
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity_change',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='route_of_administration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='medicationprescription',
            name='quantity_dispensed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicationprescription',
            name='quantity_prescribed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicationprescription',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('dispensed', 'Dispensed')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='employee_type',
            field=models.CharField(default='full_time', max_length=20),
        ),
    ]
