# Generated by Django 5.2 on 2026-02-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_inventorytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationgenericname',
            options={'ordering': ['name'], 'verbose_name': 'Medication Generic Name', 'verbose_name_plural': 'Medication Generic Names'},
        ),
        migrations.AlterModelOptions(
            name='medicationinventory',
            options={'ordering': ['medication__name'], 'verbose_name': 'Medication Inventory', 'verbose_name_plural': 'Medication Inventories'},
        ),
        migrations.AlterModelOptions(
            name='medicationprescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medication Prescription', 'verbose_name_plural': 'Medication Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='medicationtype',
            options={'ordering': ['name'], 'verbose_name': 'Medication Type', 'verbose_name_plural': 'Medication Types'},
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('addition', 'Stock Addition'), ('dispensation', 'Dispensation'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('expired', 'Expired/Disposed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='route_of_administration',
            field=models.CharField(choices=[('oral', 'Oral'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current quantity in stock'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum quantity before reorder'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='employee_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
    ]
