# Generated by Django 5.2 on 2025-04-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Consultation Location',
                'verbose_name_plural': 'Consultation Locations',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consultation Reason',
                'verbose_name_plural': 'Consultation Reasons',
                'ordering': ['reason'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Medical Specialty',
                'verbose_name_plural': 'Medical Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.medicalspecialty')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physician',
                'verbose_name_plural': 'Physicians',
                'ordering': ['username__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('consultation_date_date_only', models.DateField(default=None)),
                ('consultation_time_block', models.CharField(choices=[('BLOCK_01', '00:00'), ('BLOCK_02', '00:30'), ('BLOCK_03', '01:00'), ('BLOCK_04', '01:30'), ('BLOCK_05', '02:00'), ('BLOCK_06', '02:30'), ('BLOCK_07', '03:00'), ('BLOCK_08', '03:30'), ('BLOCK_09', '04:00'), ('BLOCK_10', '04:30'), ('BLOCK_11', '05:00'), ('BLOCK_12', '05:30'), ('BLOCK_13', '06:00'), ('BLOCK_14', '06:30'), ('BLOCK_15', '07:00'), ('BLOCK_16', '07:30'), ('BLOCK_17', '08:00'), ('BLOCK_18', '08:30'), ('BLOCK_19', '09:00'), ('BLOCK_20', '09:30'), ('BLOCK_21', '10:00'), ('BLOCK_22', '10:30'), ('BLOCK_23', '11:00'), ('BLOCK_24', '11:30'), ('BLOCK_25', '12:00'), ('BLOCK_26', '12:30'), ('BLOCK_27', '13:00'), ('BLOCK_28', '13:30'), ('BLOCK_29', '14:00'), ('BLOCK_30', '14:30'), ('BLOCK_31', '15:00'), ('BLOCK_32', '15:30'), ('BLOCK_33', '16:00'), ('BLOCK_34', '16:30'), ('BLOCK_35', '17:00'), ('BLOCK_36', '17:30'), ('BLOCK_37', '18:00'), ('BLOCK_38', '18:30'), ('BLOCK_39', '19:00'), ('BLOCK_40', '19:30'), ('BLOCK_41', '20:00'), ('BLOCK_42', '20:30'), ('BLOCK_43', '21:00'), ('BLOCK_44', '21:30'), ('BLOCK_45', '22:00'), ('BLOCK_46', '22:30'), ('BLOCK_47', '23:00'), ('BLOCK_48', '23:30')], default='BLOCK_01', max_length=20)),
                ('is_an_emergency', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdl_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdl.pdlprofile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultationlocation')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultationreason')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.physician')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['consultation_date_date_only', 'consultation_time_block'],
                'constraints': [models.UniqueConstraint(fields=('pdl_profile', 'consultation_date_date_only', 'consultation_time_block'), name='unique_consultation_per_pdl_per_time_block'), models.UniqueConstraint(fields=('physician', 'consultation_date_date_only', 'consultation_time_block'), name='unique_consultation_per_physician_per_time_block'), models.UniqueConstraint(fields=('location', 'consultation_date_date_only', 'consultation_time_block'), name='unique_consultation_per_location_per_time_block')],
            },
        ),
    ]
