# Generated by Django 5.2 on 2025-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_time_block',
            field=models.CharField(choices=[('BLOCK_08_00', '8:00 AM'), ('BLOCK_08_30', '8:30 AM'), ('BLOCK_09_00', '9:00 AM'), ('BLOCK_09_30', '9:30 AM'), ('BLOCK_10_00', '10:00 AM'), ('BLOCK_10_30', '10:30 AM'), ('BLOCK_11_00', '11:00 AM'), ('BLOCK_11_30', '11:30 AM'), ('BLOCK_13_00', '1:00 PM'), ('BLOCK_13_30', '1:30 PM'), ('BLOCK_14_00', '2:00 PM'), ('BLOCK_14_30', '2:30 PM'), ('BLOCK_15_00', '3:00 PM'), ('BLOCK_15_30', '3:30 PM'), ('BLOCK_16_00', '4:00 PM'), ('BLOCK_16_30', '4:30 PM'), ('BLOCK_17_00', '5:00 PM')], default='BLOCK_08_00', max_length=20),
        ),
    ]
