# Generated by Django 5.2 on 2025-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_consultation_time_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='pea_abdomen',
            field=models.TextField(blank=True, null=True, verbose_name='Abdomen'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Blood pressure (mmHg)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Body Mass Index (BMI)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_chest_lungs',
            field=models.TextField(blank=True, null=True, verbose_name='Chest/Lungs'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_complaining',
            field=models.BooleanField(default=False, verbose_name='Complaining on arrival'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_extremities',
            field=models.TextField(blank=True, null=True, verbose_name='Extremities'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_general_appearance',
            field=models.TextField(blank=True, null=True, verbose_name='General appearance'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_genito_urinary',
            field=models.TextField(blank=True, null=True, verbose_name='Genito-urinary tract'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_head_eyes_ears_nose_throat',
            field=models.TextField(blank=True, null=True, verbose_name='Head, eyes, ears, nose, throat'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_heart',
            field=models.TextField(blank=True, null=True, verbose_name='Heart'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heart rate (bpm)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_musculoskeletal',
            field=models.TextField(blank=True, null=True, verbose_name='Musculoskeletal system'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_neck',
            field=models.TextField(blank=True, null=True, verbose_name='Neck'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_other_findings',
            field=models.TextField(blank=True, null=True, verbose_name='Other significant findings'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_rr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Respiratory rate (breaths/min)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pea_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_alcohol_drinker',
            field=models.BooleanField(default=False, verbose_name='Alcohol drinker'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_arv_details',
            field=models.TextField(blank=True, null=True, verbose_name='ARV treatment details'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_arv_treatment',
            field=models.BooleanField(default=False, verbose_name='ARV treatment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Blood type'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_family_history',
            field=models.CharField(blank=True, choices=[('HTN', 'Hypertension'), ('STROKE', 'Stroke'), ('MI', 'Heart attack'), ('DM', 'Diabetes'), ('ASTHMA', 'Asthma'), ('CKD', 'Kidney disease'), ('CA', 'Cancer')], help_text='Select one family history condition', max_length=50, null=True, verbose_name='Family history'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_illicit_drugs',
            field=models.BooleanField(default=False, verbose_name='Use of illicit drugs'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_limitations',
            field=models.TextField(blank=True, null=True, verbose_name='Limitations on range of motion and activities'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_major_adult_illnesses',
            field=models.TextField(blank=True, null=True, verbose_name='Major adult illnesses'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_major_surgeries',
            field=models.TextField(blank=True, null=True, verbose_name='Major surgeries'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_medication_history',
            field=models.TextField(blank=True, null=True, verbose_name='Medication history'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_mental_emotional',
            field=models.TextField(blank=True, null=True, verbose_name='Mental and emotional problems'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_pediatric_history',
            field=models.TextField(blank=True, null=True, verbose_name='Pediatric history'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_poly_drug_use',
            field=models.BooleanField(default=False, verbose_name='Uses more than one drug at a time'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_psychiatric_facility',
            field=models.BooleanField(default=False, verbose_name='Confinement in a psychiatric facility'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_psychiatric_history',
            field=models.BooleanField(default=False, verbose_name='Past psychiatric history'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_psychiatric_when',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='If yes, when'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_serious_injuries',
            field=models.TextField(blank=True, null=True, verbose_name='Serious physical injuries'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_smoking',
            field=models.CharField(blank=True, choices=[('NEVER', 'Never smoked'), ('CURRENT', 'Current smoker'), ('PASSIVE', 'Passive smoker'), ('STOPPED', 'Stopped > 1 year')], max_length=10, null=True, verbose_name='Smoking history'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_transfusions_reactions',
            field=models.TextField(blank=True, null=True, verbose_name='History of transfusions/BT reactions'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pmh_vaccines',
            field=models.TextField(blank=True, null=True, verbose_name='Vaccines'),
        ),
    ]
