# Generated by Django 5.2 on 2025-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_pea_abdomen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='pea_complaining',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_abdomen',
            field=models.BooleanField(default=False, verbose_name='Complaining: Abdomen'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_chest_lungs',
            field=models.BooleanField(default=False, verbose_name='Complaining: Chest/Lungs'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_extremities',
            field=models.BooleanField(default=False, verbose_name='Complaining: Extremities'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_general_appearance',
            field=models.BooleanField(default=False, verbose_name='Complaining: General appearance'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_genito_urinary',
            field=models.BooleanField(default=False, verbose_name='Complaining: Genito-urinary tract'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_head_eyes_ears_nose_throat',
            field=models.BooleanField(default=False, verbose_name='Complaining: Head/Eyes/Ears/Nose/Throat'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_heart',
            field=models.BooleanField(default=False, verbose_name='Complaining: Heart'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_musculoskeletal',
            field=models.BooleanField(default=False, verbose_name='Complaining: Musculoskeletal system'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pea_neck',
            field=models.BooleanField(default=False, verbose_name='Complaining: Neck'),
        ),
    ]
