# Generated by Django 5.2 on 2025-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_remove_consultation_pea_complaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='fr_conclusion',
            field=models.CharField(blank=True, choices=[('HEALTHY', 'Practically healthy'), ('SBIRT', 'SBIRT'), ('PHILPEN', 'PhilPEN'), ('NEURO_PSYCH', 'Neuro-psychiatric evaluation'), ('ILL_TREATMENT', 'Further documentation of allegations of ill-treatment')], max_length=30, null=True, verbose_name='Final conclusion'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fr_other_impressions',
            field=models.TextField(blank=True, null=True, verbose_name='Other impressions'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fr_recommendation',
            field=models.CharField(blank=True, choices=[('DORM', 'To be accommodated in general dormitory'), ('ISOLATED', 'To be isolated'), ('HOSPITAL', 'To be hospitalized')], max_length=20, null=True, verbose_name='Recommendation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_blood_streaked_sputum',
            field=models.BooleanField(default=False, verbose_name='Blood-streaked sputum'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_bmi_less_18_5',
            field=models.BooleanField(default=False, verbose_name='BMI < 18.5'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_cxr_suggestive',
            field=models.BooleanField(default=False, verbose_name='Chest X-ray suggestive of TB'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_exposure',
            field=models.BooleanField(default=False, verbose_name='History of TB exposure'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_previous_treatment',
            field=models.BooleanField(default=False, verbose_name='History of previous TB treatment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_remarks',
            field=models.CharField(blank=True, choices=[('PRESUMPTIVE_TB', 'Presumptive TB'), ('PRESUMPTIVE_DR_TB', 'Presumptive DR-TB'), ('NOT_TB', 'Not TB'), ('ONGOING_TB', 'Ongoing TB'), ('OTHER_FU', 'Other follow-up')], max_length=20, null=True, verbose_name='TB remarks'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tb_unexplained_cough',
            field=models.BooleanField(default=False, verbose_name='Unexplained cough'),
        ),
    ]
