# Generated by Django 5.2 on 2025-09-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_fr_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultationlocation'),
        ),
    ]
