# Generated by Django 5.2 on 2026-03-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='followup_days',
            field=models.IntegerField(default=7, verbose_name='Days until follow-up'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='followup_scheduled',
            field=models.BooleanField(default=False, verbose_name='Follow-up has been scheduled'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_followup',
            field=models.BooleanField(default=False, verbose_name='Is a follow-up consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='parent_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='consultations.consultation', verbose_name='Parent consultation'),
        ),
    ]
